### ISSUE TITLE
Require period parameter instead of cycle in getTimestampPlusPeriod

### ISSUE THREAD

**Issue by nbundi** [atpar/actus-solidity#17]
Currently, a cycle parameter is required as input for calculating a timestamp+period. however, the stub-parameter within a cycle has no effect and, as a result, the function cannot be used with a period argument only. 

See here: https://github.com/atpar/actus-solidity/blob/faad153225cf4b809fd31a3d9cff1197a7fbd750/contracts/Core/Utils.sol#L10

**Comment by jo-es** [comment]
already fixed in #16 

see: https://github.com/atpar/actus-solidity/blob/feature/AP-28-contract-status/contracts/Core/Utils.sol
